import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Loader from "@/components/loader";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loading, setLoading] = useState(true);

  return (
    <>
      <div className="flex max-w-5xl mx-auto flex-col items-center justify-center py-2 min-h-screen">
        <Head>
          <title>Lighthouse Pagespeed API</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <main className="flex flex-1 w-full flex-col items-center justify-center text-center px-4 mt-12 sm:mt-20">
          <h1 className="sm:text-6xl text-4xl max-w-2xl font-bold text-slate-900">
            Lighthouse Pagespeed API with Vercel Edge
          </h1>
          <div className="max-w-screen-lg my-12 mx-auto">
            <a
              href="https://lighthouse-api.vercel.app/api/score?url=https://lighthouse-api.vercel.app/"
              target="_blank"
              rel="noopener noreferrer">
              <pre className="bg-gray-100 px-5 py-2 rounded-md">
                GET https://lighthouse-api.vercel.app/api/score?url=
                <strong>https://yourwebsiteurl.com/</strong>
              </pre>
            </a>
          </div>
          <a
            className="flex max-w-fit items-center justify-center space-x-2 rounded-full border border-gray-300 bg-white px-4 py-2 text-sm text-gray-600 shadow-md transition-colors hover:bg-gray-100 mb-5"
            href="https://github.com/surjithctly/lighthouse-api"
            target="_blank"
            rel="noopener noreferrer">
            {/* <Github /> */}
            <p>Star on GitHub</p>
          </a>

          {/* <div className="flex mt-10 items-center space-x-3">

              <p className="text-left font-medium">
                Copy your current bio{" "}
                <span className="text-slate-500">
                  (or write a few sentences about yourself)
                </span>
                .
              </p>
            </div>
            <textarea
              // value={bio}
              // onChange={(e) => setBio(e.target.value)}
              rows={4}
              className="w-full rounded-md border-gray-300 shadow-sm focus:border-black focus:ring-black my-5"
              placeholder={
                "e.g. Senior Developer Advocate @vercel. Tweeting about web development, AI, and React / Next.js. Writing nutlope.substack.com."
              }
            />
            <div className="flex mb-5 items-center space-x-3">

              <p className="text-left font-medium">Select your vibe.</p>
            </div>
            <div className="block">

            </div>

            {!loading && (
              <button
                className="bg-black rounded-xl text-white font-medium px-4 py-2 sm:mt-10 mt-8 hover:bg-black/80 w-full"
                onClick={(e) => console.log(e)}>
                Generate your bio &rarr;
              </button>
            )}
            {loading && (
              <button
                className="bg-black rounded-xl text-white font-medium px-4 py-2 sm:mt-10 mt-8 hover:bg-black/80 w-full"
                disabled>
                <Loader />
              </button>
            )}
          </div>

          <hr className="h-px bg-gray-700 border-1 dark:bg-gray-700" />
          <div>Result</div> */}
        </main>
        <Footer />
      </div>
    </>
  );
}
